/*
 * rsym_https.h: a small blocking HTTP(S)/1.1 client (mbedTLS over rsym_tcp),
 * for use from a worker thread. One request per connection.
 * Certificates are checked against rsym_ca_google_pem (Google's roots)
 * unless rsym_https_set_ca() picked another bundle.
 */
#ifndef RSYM_HTTPS_H
#define RSYM_HTTPS_H

#ifdef __cplusplus
extern "C" {
#endif

/* Receives the response body in pieces; return 0 to continue, non-zero to
 * abort the transfer. */
typedef int (*rsym_http_body_fn)(void *ctx, const unsigned char *data, int len);
/* Receives the status and the raw header block (lines separated by "\r\n",
 * status line first) once they have arrived, before any body; return 0 to
 * continue, non-zero to stop (the request then still returns 0). */
typedef int (*rsym_http_head_fn)(void *ctx, int status, const char *headers);

typedef struct rsym_http_request {
    const char *method;         /* "GET", "POST", ... */
    const char *host;           /* also used for SNI and the Host header */
    int port;                   /* 0 means 443 */
    const char *path;           /* e.g. "/drive/v3/files?q=..." (URL-encoded) */
    const char *headers;        /* extra lines, each ending "\r\n", or NULL */
    const void *body;           /* request body or NULL */
    int body_len;
    int timeout_ms;             /* per network operation; 0 means 30 s */
    rsym_http_body_fn on_body;  /* stream the body here instead of buffering */
    void *body_ctx;             /* passed to on_body and on_headers */
    /* Optional; leave zeroed for the defaults. */
    int plain;                  /* 1: plain HTTP, no TLS (port 0 means 80) */
    const char *user_agent;     /* replaces the default User-Agent */
    rsym_http_head_fn on_headers;
    volatile int *cancel;       /* set non-zero (any thread) to stop early */
} rsym_http_request;

typedef struct rsym_http_response {
    int status;                 /* HTTP status, e.g. 200 */
    char *headers;              /* raw header block, NUL-terminated */
    unsigned char *body;        /* buffered body (NUL-terminated), unless on_body */
    int body_len;
    char error[192];            /* set when rsym_https_request fails */
    int cert_error;             /* 1 if it failed on certificate checks */
    int cancelled;              /* 1 if stopped by *req->cancel */
} rsym_http_response;

/* Root certificates (PEM, NUL-terminated), generated by tools/gen-ca.py. */
extern const char rsym_ca_google_pem[];

/* Use another set of root certificates (PEM, NUL-terminated, kept by the
 * caller). Call before the first request. */
void rsym_https_set_ca(const char *pem);

/* Initialise PSA crypto and parse the root certificates. Called by
 * rsym_https_request on first use; 0 on success. Not thread-safe: the
 * first call must not race with another. */
int rsym_https_init(void);

/* Perform one request. Returns 0 if a response was received (any status),
 * negative on failure with resp->error describing it. Free with
 * rsym_http_response_free either way. */
int rsym_https_request(const rsym_http_request *req, rsym_http_response *resp);
void rsym_http_response_free(rsym_http_response *resp);

/* Copy the value of header `name` (case-insensitive) into buf; returns buf,
 * or NULL if absent. */
char *rsym_http_header(const rsym_http_response *resp, const char *name,
                       char *buf, int buflen);

#ifdef __cplusplus
}
#endif

#endif
