#!/usr/bin/env python3
"""Generate driver/rtlu_tables.cpp from Linux's rtlwifi rtl8192cu/table.c.

    tools/gen-tables.py path/to/rtl8192cu/table.c > driver/rtlu_tables.cpp

Only the tables a receive-only bring-up needs are kept: MAC, baseband (PHY_REG),
AGC and radio, in the normal and high-PA variants. The PHY_REG_PG tables are
per-rate TX power offsets and are left out.
"""
import re
import sys

# Linux array name -> our name
TABLES = [
    ("RTL8192CUMAC_2T_ARRAY", "rtlu_mac"),
    ("RTL8192CUPHY_REG_2TARRAY", "rtlu_phy_2t"),
    ("RTL8192CUPHY_REG_1TARRAY", "rtlu_phy_1t"),
    ("RTL8192CUPHY_REG_1T_HPARRAY", "rtlu_phy_1t_hp"),
    ("RTL8192CUAGCTAB_2TARRAY", "rtlu_agc_2t"),
    ("RTL8192CUAGCTAB_1TARRAY", "rtlu_agc_1t"),
    ("RTL8192CUAGCTAB_1T_HPARRAY", "rtlu_agc_1t_hp"),
    ("RTL8192CURADIOA_2TARRAY", "rtlu_radioa_2t"),
    ("RTL8192CU_RADIOB_2TARRAY", "rtlu_radiob_2t"),
    ("RTL8192CU_RADIOA_1TARRAY", "rtlu_radioa_1t"),
    ("RTL8192CURADIOA_1T_HPARRAY", "rtlu_radioa_1t_hp"),
]


def main():
    src = open(sys.argv[1]).read()
    out = [
        "/*",
        " * rtlu_tables.cpp: RTL8188CU/8192CU register tables (address/value",
        " * pairs), generated by tools/gen-tables.py from Linux",
        " * drivers/net/wireless/realtek/rtlwifi/rtl8192cu/table.c",
        " * (Copyright(c) 2009-2012 Realtek Corporation, GPL-2.0). Do not edit.",
        " */",
        '#include "rtlu_int.h"',
        "",
    ]
    for linux_name, name in TABLES:
        m = re.search(r"\b%s\[[^\]]*\]\s*=\s*\{(.*?)\};" % linux_name, src, re.S)
        if not m:
            sys.exit("table %s not found" % linux_name)
        vals = re.findall(r"0x[0-9a-fA-F]+|\b\d+\b", m.group(1))
        if len(vals) % 2:
            sys.exit("table %s has an odd length" % linux_name)
        out.append("const uint32_t %s[] = {" % name)
        for i in range(0, len(vals), 2):
            out.append("    0x%08x, 0x%08x," % (int(vals[i], 0), int(vals[i + 1], 0)))
        out.append("};")
        out.append("const int %s_len = %d;" % (name, len(vals)))
        out.append("")
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
