#!/usr/bin/env python3
"""Generate group/rssh.mmp from group/core-sources.txt (PuTTY files) plus
rSSH's own sources. Re-run after changing the source list or PuTTY version."""
import collections, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
core = [l.strip() for l in open(os.path.join(ROOT, 'group/core-sources.txt')) if l.strip()]

bydir = collections.OrderedDict()
for f in core:
    d, b = os.path.split(f)
    bydir.setdefault('../putty/' + d if d else '../putty', []).append(b)
bydir['../symbian'] = ['be_list_rssh.c', 'stubs.c', 'frontend.c', 'trace.c', 'network.c']

# PuTTY's headers (bidi.h, ...) collide with Nokia's, so the C core is a
# static library built with PuTTY's include path, and the C++ app never
# sees it.
lib = ["""// rssh_core.mmp - GENERATED by tools/gen-mmp.py, do not edit by hand.
// PuTTY 0.85 portable core + rSSH's C platform/front-end code.

TARGET          rssh_core.lib
TARGETTYPE      lib
UID             0 0xE5A1E010

MACRO           HAVE_CMAKE_H

USERINCLUDE     ../symbian ../putty ../putty/terminal ../putty/charset ../putty/generated
USERINCLUDE     ../../common/net
SYSTEMINCLUDE   ../symbian/sysinclude /epoc32/include/stdapis /epoc32/include
"""]
for d, files in bydir.items():
    lib.append('\nSOURCEPATH      %s\n' % d)
    for f in sorted(files):
        lib.append('SOURCE          %s\n' % f)
open(os.path.join(ROOT, 'group/rssh_core.mmp'), 'w').write(''.join(lib))

exe = """// rssh.mmp - GENERATED by tools/gen-mmp.py, do not edit by hand.
// rSSH: SSH client for Symbian^3 on PuTTY 0.85 (experimental).
// 0xE....... is the unprotected test-UID range: fine for self-signed builds.

TARGET          rssh.exe
TARGETTYPE      exe
UID             0x100039CE 0xE5A1E010
SECUREID        0xE5A1E010
VENDORID        0
CAPABILITY      NetworkServices
EPOCSTACKSIZE   0x14000
EPOCHEAPSIZE    0x10000 0x1000000

USERINCLUDE     ../symbian ../src ../../common/net
SYSTEMINCLUDE   /epoc32/include /epoc32/include/mw /epoc32/include/platform
SYSTEMINCLUDE   /epoc32/include/platform/mw /epoc32/include/stdapis

SOURCEPATH      ../data
START RESOURCE  rssh.rss
HEADER
TARGETPATH      /resource/apps
END
START RESOURCE  rssh_reg.rss
TARGETPATH      /private/10003a3f/import/apps
END

SOURCEPATH      ../symbian
SOURCE          platform.cpp
SOURCE          sock.cpp
SOURCEPATH      ../src
SOURCE          rssh.cpp
// the remote debug log, compiled in (rSSH does not link rsym_net.lib)
SOURCEPATH      ../../common/net
SOURCE          rsym_rlog.cpp

STATICLIBRARY   rssh_core.lib
LIBRARY         euser.lib apparc.lib cone.lib eikcore.lib avkon.lib
LIBRARY         eikdlg.lib eikctl.lib eikcoctl.lib efsrv.lib gdi.lib
LIBRARY         hal.lib random.lib charconv.lib esock.lib insock.lib bafl.lib
LIBRARY         libc.lib libm.lib
"""
open(os.path.join(ROOT, 'group/rssh.mmp'), 'w').write(exe)
print('wrote group/rssh_core.mmp (%d sources) and group/rssh.mmp'
      % sum(len(v) for v in bydir.values()))

# ---- About page text: about.txt + PuTTY's LICENCE -> src/about_text.h ----
about = open(os.path.join(ROOT, 'about.txt'), encoding='utf-8').read().rstrip('\n')
licence = open(os.path.join(ROOT, 'putty', 'LICENCE'), encoding='utf-8').read().rstrip('\n')
text = about + '\n' + licence + '\n'
def c_escape(t):
    out = []
    for b in t.encode('utf-8'):
        c = chr(b)
        if c == '\\': out.append('\\\\')
        elif c == '"': out.append('\\"')
        elif c == '\n': out.append('\\n"\n    "')
        elif 32 <= b < 127: out.append(c)
        else: out.append('\\%03o' % b)
    return ''.join(out)
open(os.path.join(ROOT, 'src/about_text.h'), 'w').write(
    '/* about_text.h - GENERATED by tools/gen-mmp.py from about.txt and\n'
    ' * putty/LICENCE; edit those instead. UTF-8. */\n'
    'static const char KAboutTextUtf8[] =\n    "' + c_escape(text) + '";\n')
print('wrote src/about_text.h')
