#!/usr/bin/env python3
"""Generate group/rsym_mbedtls.mmp (static library: mbedTLS + Symbian glue)
from group/mbedtls-sources.txt and group/mbedtls-includes.txt. Re-run after
upgrading mbedTLS (refresh those two lists from its CMake build first)."""
import collections, os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
def lines(name):
    return [l.strip() for l in open(os.path.join(ROOT, 'group', name)) if l.strip()]

bydir = collections.OrderedDict()
for f in lines('mbedtls-sources.txt'):
    d, b = os.path.split(f)
    bydir.setdefault('../mbedtls/' + d, []).append(b)
bydir['../mbedtls-symbian'] = ['rsym_platform.cpp']

out = ["""// rsym_mbedtls.mmp - GENERATED by tools/gen-mmp.py, do not edit by hand.
// mbedTLS (TLS 1.2/1.3, X.509, PSA crypto) for Symbian^3, as a static library.
// Link with: STATICLIBRARY rsym_mbedtls.lib (plus euser.lib random.lib libc.lib)

TARGET          rsym_mbedtls.lib
TARGETTYPE      lib
UID             0 0

// Our config overrides (mbedtls-symbian/rsym_*_config.h) are selected by
// patches/0001-symbian-user-config.patch whenever __SYMBIAN32__ is defined.

USERINCLUDE     ../mbedtls-symbian
"""]
# abld (and makmake's dependency scan) pass -I-, which stops the preprocessor
# looking in a header's own directory for "..." includes; mbedTLS relies on
# that, so every directory holding headers goes on the include path.
incdirs = list(lines('mbedtls-includes.txt'))
for dirpath, dirs, files in sorted(os.walk(os.path.join(ROOT, 'mbedtls'))):
    rel = os.path.relpath(dirpath, os.path.join(ROOT, 'mbedtls'))
    if rel.split(os.sep)[0] in ('tests', 'programs', 'framework', 'docs', 'doxygen') \
       or '/tests' in rel or '/programs' in rel or rel.startswith('tf-psa-crypto/framework'):
        continue
    if any(f.endswith('.h') for f in files) and rel not in incdirs:
        incdirs.append(rel)
open(os.path.join(ROOT, 'group', 'mbedtls-includes-all.txt'), 'w').write('\n'.join(incdirs) + '\n')
for d in incdirs:
    out.append('USERINCLUDE     ../mbedtls/%s\n' % d)
# mbedTLS also includes its public headers as <psa/...>, <mbedtls/...>; with
# -I- those are only searched for in the system include directories.
for d in lines('mbedtls-includes.txt'):
    out.append('SYSTEMINCLUDE   ../mbedtls/%s\n' % d)
out.append('SYSTEMINCLUDE   ../mbedtls-symbian\n')
out.append('SYSTEMINCLUDE   /epoc32/include/stdapis /epoc32/include\n')
for d, files in bydir.items():
    out.append('\nSOURCEPATH      %s\n' % d)
    for f in sorted(files):
        out.append('SOURCE          %s\n' % f)
open(os.path.join(ROOT, 'group/rsym_mbedtls.mmp'), 'w').write(''.join(out))
print('wrote group/rsym_mbedtls.mmp (%d sources)' % sum(len(v) for v in bydir.values()))

# ---- rsym_net.lib: TCP (RSocket), HTTPS (mbedTLS), CA bundle, debug log ----
net = ["""// rsym_net.mmp - GENERATED by tools/gen-mmp.py, do not edit by hand.
// Blocking TCP/HTTPS client and debug log for Symbian apps (see net/*.h).
// Link with: STATICLIBRARY rsym_net.lib rsym_mbedtls.lib
//            LIBRARY esock.lib insock.lib random.lib libc.lib euser.lib

TARGET          rsym_net.lib
TARGETTYPE      lib
UID             0 0

USERINCLUDE     ../net ../mbedtls-symbian
"""]
for d in incdirs:
    net.append('USERINCLUDE     ../mbedtls/%s\n' % d)
for d in lines('mbedtls-includes.txt'):
    net.append('SYSTEMINCLUDE   ../mbedtls/%s\n' % d)
net.append('SYSTEMINCLUDE   ../mbedtls-symbian\n')
net.append('SYSTEMINCLUDE   /epoc32/include/stdapis /epoc32/include\n')
net.append('SYSTEMINCLUDE   /epoc32/include/mw /epoc32/include/platform /epoc32/include/platform/mw\n')
net.append('\nSOURCEPATH      ../net\n')
for f in sorted(os.listdir(os.path.join(ROOT, 'net'))):
    if f.endswith(('.c', '.cpp')):
        net.append('SOURCE          %s\n' % f)
open(os.path.join(ROOT, 'group/rsym_net.mmp'), 'w').write(''.join(net))
print('wrote group/rsym_net.mmp')
