#!/usr/bin/env python3
"""Generate net/rsym_ca_google.c: the root certificates Google's APIs chain
to, taken from curl's copy of the Mozilla CA bundle.

    curl -O https://curl.se/ca/cacert.pem -O https://curl.se/ca/cacert.pem.sha256
    sha256sum -c cacert.pem.sha256
    python3 tools/gen-ca.py path/to/cacert.pem

Google API hosts chain to GTS Root R1 (RSA) or GTS Root R4 (ECDSA); R3 is
kept as the ECDSA sibling. Add names to ROOTS to trust more CAs."""
import hashlib, os, re, sys

ROOTS = ['GTS Root R1', 'GTS Root R3', 'GTS Root R4']

src = sys.argv[1]
data = open(src, encoding='utf-8').read()
sha = hashlib.sha256(open(src, 'rb').read()).hexdigest()
date = re.search(r'Certificate data from Mozilla as of: (.*)', data)
pems = []
for name in ROOTS:
    m = re.search(r'^%s\n=+\n(-----BEGIN CERTIFICATE-----\n.*?-----END CERTIFICATE-----\n)'
                  % re.escape(name), data, re.S | re.M)
    if not m:
        sys.exit('not found in bundle: ' + name)
    pems.append((name, m.group(1)))

out = ['/* rsym_ca_google.c - GENERATED by tools/gen-ca.py, do not edit by hand.\n',
       ' * Root CAs for Google APIs, from the Mozilla bundle (curl cacert.pem)\n',
       ' * %s, SHA-256 %s. */\n\n' % (date.group(1).strip() if date else '?', sha),
       '#include "rsym_https.h"\n\n',
       '/* PEM, NUL-terminated (mbedtls_x509_crt_parse wants the NUL counted). */\n',
       'const char rsym_ca_google_pem[] =\n']
for name, pem in pems:
    out.append('    /* %s */\n' % name)
    for line in pem.splitlines():
        out.append('    "%s\\n"\n' % line)
out.append('    ;\n')
open(os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                  'net', 'rsym_ca_google.c'), 'w').write(''.join(out))
print('wrote net/rsym_ca_google.c with', ', '.join(n for n, _ in pems))
