#!/usr/bin/env python3
"""Stage NetSurf's resources in apps/netsurf/build/res (symlinks resolved)
and write sis/netsurf.pkg listing them. Run by apps/netsurf/prebuild.sh."""
import os, shutil

HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.dirname(HERE)
NS = os.path.join(APP, 'src', 'netsurf')
FBRES = os.path.join(NS, 'frontends', 'framebuffer', 'res')
GENRES = os.path.join(APP, 'gen', 'netsurf', 'frontends', 'framebuffer', 'res')
OUT = os.path.join(APP, 'build', 'res')
PRIV = '!:\\private\\E5A1E030\\res\\'

files = {   # name in res/ -> source
    'Messages': os.path.join(GENRES, 'en', 'Messages'),
    'en/Messages': os.path.join(GENRES, 'en', 'Messages'),
    'ca-bundle': os.path.join(NS, 'resources', 'ca-bundle'),
    'Choices': os.path.join(APP, 'data', 'Choices'),
}
for name in ('adblock.css', 'default.css', 'internal.css', 'quirks.css',
             'welcome.html', 'credits.html', 'licence.html',
             'netsurf.png', 'favicon.png'):
    files[name] = os.path.realpath(os.path.join(FBRES, name))
for d in ('icons',):
    for f in sorted(os.listdir(os.path.join(FBRES, d))):
        files[d + '/' + f] = os.path.realpath(os.path.join(FBRES, d, f))

if os.path.isdir(OUT):
    shutil.rmtree(OUT)
lines = []
for name in sorted(files):
    src = files[name]
    dst = os.path.join(OUT, name)
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    shutil.copyfile(src, dst)
    lines.append('"..\\build\\res\\%s" -"%s%s"' % (name.replace('/', '\\'), PRIV,
                                                    name.replace('/', '\\')))

pkg = r'''; NetSurf installation package - GENERATED by apps/netsurf/tools/gen-pkg.py
; (built with: ./sym sh env/build.sh apps/netsurf)
&EN
#{"NetSurf"},(0xE5A1E030),0,1,0
%{"SymbianApps"}
:"SymbianApps"

; Symbian^3 product ID (E7, N8, C7, ...; also covers Anna/Belle)
[0x20022E6D],0,0,0,{"S60ProductID"}

"$(EPOCROOT)epoc32\release\gcce\urel\netsurf.exe"                      -"!:\sys\bin\netsurf.exe"
"$(EPOCROOT)epoc32\data\z\resource\apps\netsurf.rsc"                   -"!:\resource\apps\netsurf.rsc"
"$(EPOCROOT)epoc32\data\z\private\10003a3f\import\apps\netsurf_reg.rsc" -"!:\private\10003a3f\import\apps\netsurf_reg.rsc"
; app icon (SVG)
"..\build\icon\netsurf_aif.mif"                                     -"!:\resource\apps\netsurf_aif.mif"

; resources (same drive as the program: NetSurf looks on the current drive)
'''
os.makedirs(os.path.join(APP, 'sis'), exist_ok=True)
open(os.path.join(APP, 'sis', 'netsurf.pkg'), 'w').write(pkg + '\n'.join(lines) + '\n')
print('staged %d resource files; wrote sis/netsurf.pkg' % len(files))
