#!/bin/sh
# Fetch upstream PuTTY source for rSSH into apps/rssh/putty (git-ignored), verify
# it, and generate the two files PuTTY's CMake build normally creates.
# Runs on the HOST (needs wget/curl, gpg, perl).
set -e
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VER=0.85
SHA256=13fd4db2936d03b73812a7bcc2a658e4dd29cc776a56c3670a7fc6f1a0ee8af8
COMMIT=a3cce3a48d4ab12e0fccb32998b9042d4f7c3ff1   # from the release tarball
# "PuTTY Releases" 2026 release key, as listed on
# https://www.chiark.greenend.org.uk/~sgtatham/putty/keys.html
FPR=1A07DAC0F220CF12248EA7195C67D0F88BC3E5B5
URL=https://the.earth.li/~sgtatham/putty/$VER/putty-$VER.tar.gz

DL="$ROOT/downloads/putty"
mkdir -p "$DL"
cd "$DL"
[ -s putty-$VER.tar.gz ] || wget -q "$URL"
[ -s putty-$VER.tar.gz.gpg ] || wget -q "$URL.gpg"
echo "$SHA256  putty-$VER.tar.gz" | sha256sum -c -
G=$(mktemp -d)
trap 'rm -rf "$G"' EXIT
gpg -q --homedir "$G" --import "$ROOT/env/putty-release-key-2026.asc" 2>/dev/null
gpg --homedir "$G" --status-fd 1 --verify putty-$VER.tar.gz.gpg putty-$VER.tar.gz 2>/dev/null \
    | grep -q "VALIDSIG $FPR" || { echo "PGP signature check FAILED" >&2; exit 1; }
echo "signature OK (PuTTY Releases, $FPR)"

DEST="$ROOT/apps/rssh/putty"
rm -rf "$DEST" && mkdir -p "$DEST"
tar -xzf putty-$VER.tar.gz -C "$DEST" --strip-components=1
for p in "$ROOT"/apps/rssh/patches/*.patch; do
    [ -e "$p" ] || continue
    (cd "$DEST" && patch -s -p1 < "$p") && echo "applied $(basename "$p")"
done
# abld puts each source file's own directory first on the include path, so
# for the unix/*.c files rSSH reuses, unix/platform.h would shadow
# apps/rssh/symbian/platform.h. rSSH never uses the Unix one.
rm "$DEST/unix/platform.h"
mkdir -p "$DEST/generated"
(cd "$DEST" && perl charset/sbcsgen.pl -o generated/sbcsdat.c)
cat > "$DEST/generated/cmake_commit.c" <<EOC
/* cmake_commit.c - normally generated by PuTTY's CMake build. */
#include "putty.h"
const char commitid[] = "$COMMIT";
EOC
echo "==> PuTTY $VER in apps/rssh/putty"
